"""
seed_runner.py — Member A

Loads the curriculum JSON files (core_subjects.json, electives.json,
honors.json) plus exam_dates.json, computes est_difficulty/est_hours via
synthetic/generate_estimates.py, and writes one combined SQL file you
paste into Supabase's SQL Editor.

Run from the repo root:
    python database/seed/seed_runner.py

Design note: this writes a .sql file for you to paste manually, rather
than connecting directly to Supabase via the Python client. That keeps
the workflow identical to what you're already using (copy file -> paste
into SQL Editor -> Run) with no extra setup (no pip install supabase, no
service-role key handling). If you later want full automation, swap the
`write_sql_file` step for a real supabase-py client call using the
service role key from .env — the SQL string this script builds would
become the payload for that call instead.
"""

import json
import os
import sys
import uuid

# Make synthetic/ importable when running this file directly
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from synthetic.generate_estimates import estimate_difficulty_hours  # noqa: E402

CURRICULUM_DIR = os.path.join(os.path.dirname(__file__), "curriculum")
EXAM_DATES_PATH = os.path.join(os.path.dirname(__file__), "exam_dates.json")
OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "curriculum_seed.sql")


def esc(s: str) -> str:
    """Escape single quotes for SQL string literals."""
    return s.replace("'", "''")


def load_curriculum() -> list[dict]:
    subjects = []
    for filename in ("core_subjects.json", "electives.json", "honors.json"):
        path = os.path.join(CURRICULUM_DIR, filename)
        with open(path) as f:
            subjects.extend(json.load(f))
    return subjects


def load_exam_dates() -> dict:
    with open(EXAM_DATES_PATH) as f:
        data = json.load(f)
    data.pop("_comment", None)
    return data


def generate_sql(subjects: list[dict], exam_dates: dict) -> str:
    lines = []
    lines.append("-- Curriculum seed data generated by seed_runner.py")
    lines.append("-- Run this AFTER migrations 0001-0004, in Supabase's SQL Editor\n")

    skipped_exam_dates = []

    for subject in subjects:
        subject_id = str(uuid.uuid4())
        group_name_sql = f"'{esc(subject['group_name'])}'" if subject.get("group_name") else "NULL"
        lines.append(
            f"insert into subjects (id, name, category, group_name) values "
            f"('{subject_id}', '{esc(subject['name'])}', '{subject['category']}', {group_name_sql});"
        )

        if subject["name"] in exam_dates:
            for exam_type, exam_date in exam_dates[subject["name"]].items():
                lines.append(
                    f"insert into exam_dates (subject_id, exam_type, exam_date) values "
                    f"('{subject_id}', '{exam_type}', '{exam_date}');"
                )
        else:
            skipped_exam_dates.append(subject["name"])

        prev_topic_id = None  # chain topic_dependencies within this subject

        for m_idx, module in enumerate(subject["modules"], start=1):
            module_id = str(uuid.uuid4())
            lines.append(
                f"insert into modules (id, subject_id, name, order_index, assessment_phase) values "
                f"('{module_id}', '{subject_id}', '{esc(module['name'])}', {m_idx}, '{module['phase']}');"
            )

            total_topics = len(module["topics"])
            for t_idx, topic in enumerate(module["topics"], start=1):
                topic_id = str(uuid.uuid4())
                difficulty, hours = estimate_difficulty_hours(topic["type"], t_idx, total_topics)
                lines.append(
                    f"insert into topics (id, module_id, name, order_index, est_difficulty, est_hours) "
                    f"values ('{topic_id}', '{module_id}', '{esc(topic['name'])}', {t_idx}, {difficulty}, {hours});"
                )

                if prev_topic_id:
                    lines.append(
                        f"insert into topic_dependencies (topic_id, depends_on_topic_id) values "
                        f"('{topic_id}', '{prev_topic_id}');"
                    )
                prev_topic_id = topic_id

                subtopics = topic.get("subtopics", [])
                for s_idx, subtopic_name in enumerate(subtopics, start=1):
                    subtopic_id = str(uuid.uuid4())
                    sub_hours = round(hours / max(len(subtopics), 1), 2)
                    lines.append(
                        f"insert into subtopics (id, topic_id, name, order_index, est_hours) "
                        f"values ('{subtopic_id}', '{topic_id}', '{esc(subtopic_name)}', {s_idx}, {sub_hours});"
                    )

        lines.append("")

    if skipped_exam_dates:
        lines.insert(1, f"-- NOTE: no exam_dates found for: {', '.join(skipped_exam_dates)}\n")

    return "\n".join(lines), skipped_exam_dates


if __name__ == "__main__":
    subjects = load_curriculum()
    exam_dates = load_exam_dates()
    sql, skipped = generate_sql(subjects, exam_dates)

    with open(OUTPUT_PATH, "w") as f:
        f.write(sql)

    n_modules = sum(len(s["modules"]) for s in subjects)
    n_topics = sum(len(m["topics"]) for s in subjects for m in s["modules"])
    n_subtopics = sum(len(t.get("subtopics", [])) for s in subjects for m in s["modules"] for t in m["topics"])

    print(f"Generated {OUTPUT_PATH}")
    print(f"  Subjects:  {len(subjects)}")
    print(f"  Modules:   {n_modules}")
    print(f"  Topics:    {n_topics}")
    print(f"  Subtopics: {n_subtopics}")
    if skipped:
        print(f"  No exam_dates for: {', '.join(skipped)}")
